name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy mkdocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-static-i18n

      - name: Deploy documentation to GitHub Pages
        run: mkdocs gh-deploy --force
