name: Publish wborm to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # necessário para OIDC
  contents: read

jobs:
  publish:
    name: Publish to PyPI
    environment: release  # você pode mudar o nome aqui se quiser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true  # opcional: ignora se versão já estiver publicada